apiVersion: k8gb.absa.oss/v1beta1
kind: Gslb
metadata:
  name: broken-test-gslb1
spec:
  ingress:
    rules:
      - host: terratest-failover.cloud.example.com
  strategy:
    type: failover
    primaryGeoTag: eu
